services:
  mysql:
    image: mysql:8.0
    container_name: board-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board
      MYSQL_USER: board
      MYSQL_PASSWORD: board
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --lower_case_table_names=1

  redis:
    image: redis:7.2.7
    container_name: board-redis
    ports:
      - "6379:6379"

networks:
  board-app_default:
    name: board-app_default
    external: true
